- name: Add nvidia repo from PPA and install its signing key on Ubuntu target
  apt_repository:
    repo: ppa:graphics-drivers/ppa

- name: Add i386 architecture
  shell: dpkg --add-architecture i386
  ignore_errors: yes

- name: Update apt repo and cache (sudo apt update)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
    #apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade packages
  shell: pkcon update -y
  ignore_errors: yes