- name: Adding Nvidia repo on KDE Neon
  include_tasks: nvidia_neon_repo.yml
  when: ansible_distribution=="KDE neon"


- name: Adding Nvidia repo on Tumbleweed
  include_tasks: nvidia_tw_repo.yml
  when: ansible_distribution=="openSUSE Tumbleweed"



###################################################
####### Install driver packages
###################################################  

- name: Install Nvidia drivers with vulkan dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nvidia_packages }}"
  become: yes




###################################################
####### Arch tasks for installing 470 
###################################################  


## Uncomment if I'm gonna install 470 version from AUR
#- name: Uninstall newer nvidia drivers version to avoid errors
  #pacman:
    #name:
      #- nvidia-dkms
      #- nvidia-utils
      #- lib32-nvidia-utils
    #state: absent
    #force: yes
#- name: Install nvidia AUR packages
#    yay:
#      name:
#        - nvidia-470xx-dkms
#        - nvidia-470xx-utils
#        - lib32-nvidia-470xx-utils
#      state: present
#    become: yes
#  when: distro="arch"
