#######################################################
########### Install & configure grub-btrfs
#######################################################

- name: Install grub-btrfs
  pacman: 
    name: grub-btrfs
    state: present
  become: yes

#- name: Enable and start grub-btrfs.service
#  systemd:
#    name: grub-btrfs.service
#    state: enable
#    enabled: yes
#  become: yes

#- name: Enable and start grub-btrfs.service
#  systemd:
#    name: grub-btrfs.service
#    state: started
#    enabled: yes
#  become: yes
        
#- name: Enable and start grub-btrfs.path
#  systemd:
#    name: grub-btrfs.path
#    state: started
#    enabled: yes
#    ignore_errors: yes
#  become: yes

- name: Apply last config
  shell: grub-mkconfig -o /boot/grub/grub.cfg 
  become: yes