- name: Install snapper packages
  pacman:
    name:
      - snapper
      - snap-pac
    state: present
  become: yes

- name: Create snapper config for root
  shell:  snapper -c root create-config /
  ignore_errors: yes
    
#- name: Enable and start snapper scheduled snapshots
  #ansible.builtin.systemd:
    #name: snapper-timeline.timer
    #state: started
    #enabled: yes

#- name: Enable and start snapper scheduled snapshot cleanup
#  systemd:
#    name: snapper-cleanup.timer 
#    state: started
#    enabled: yes

- name: Install config file with limits for scheduled snapshots with snapper
  copy:
    src: snapshot-config
    dest: /etc/snapper/configs/config
    force: yes

 #   - name: Set snapper snapshot timer to daily
 #     lineinfile:
 #       path: /etc/systemd/system/timers.target.wants/snapper-timeline.timer
 #       search_string: 'OnCalendar'
 #       line: OnCalendar=daily

- name: Allow grub to show snapshot entries
  lineinfile:
    path: /etc/systemd/system/timers.target.wants/snapper-timeline.timer
    search_string: 'GRUB_DISABLE_RECOVERY'
    line: GRUB_DISABLE_RECOVERY=false
  become: yes